// Generated by CoffeeScript 1.10.0
(function() {
  var PageTitleChange;

  PageTitleChange = (function() {
    function PageTitleChange() {}

    PageTitleChange.prototype.init = function(title) {
      var hidden, originalTitle, state, visibilityChange;
      if (typeof document.hidden !== 'undefined') {
        hidden = 'hidden';
        visibilityChange = 'visibilitychange';
        state = 'visibilityState';
        originalTitle = document.title;
      }
      return document.addEventListener(visibilityChange, ((function(_this) {
        return function() {
          return document.title = document[state] === 'hidden' ? title : originalTitle;
        };
      })(this)), false);
    };

    return PageTitleChange;

  })();

  module.exports = PageTitleChange;

}).call(this);
